name: Generate Proto

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Go install dependencies
        run: |
          brew install protobuf 
          go get -d -u google.golang.org/grpc
          go get -d -u google.golang.org/protobuf
          export GOROOT=/usr/local/go
          export GOPATH=$HOME/go
          export GOBIN=$GOPATH/bin
          export PATH=$PATH:$GOROOT:$GOPATH:$GOBIN

      - name: Generating protos
        run: |
          protoc proto/user.proto --go_out=plugins=grpc:.

      - name: Ls
        run: ls -al

      - name: Ls
        run: ls -al /proto
        
      
