name: Generate Proto

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - uses: arduino/setup-protoc@v1
        with:
          version: '3.x'

      - name: Go install dependencies
        run: |
          go get -d github.com/golang/protobuf/protoc-gen-go
          go get -d google.golang.org/grpc/cmd/protoc-gen-go-grpc

      - name: Generating protos
        run: |
          protoc -I=$PROTO_DIR --go_out=$GEN_OUT_DIR $(find $PROTO_DIR -type f -name '*.proto')
        env:
          GEN_OUT_DIR: ./
          PROTO_DIR: proto

      - name: Ls
        run: ls -al

      - name: Ls
        run: ls -al proto/
        
      
